version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 54321:5432
    volumes:
    - ./data/db:/var/lib/postgres
    -  ./load_db.sql:/docker-entrypoint-initdb.d/load_db.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: muebles_santiago

  app:
    image: driques/monolithic-app.jar
    container_name: muebles_santiago
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/muebles_santiago
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

