-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categoria
(
    id_categoria character varying(100) COLLATE pg_catalog."default" NOT NULL,
    sueldo integer NOT NULL,
    CONSTRAINT categoria_pkey PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS public.empleado
(
    rut integer NOT NULL,
    apellidos character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nombres character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecha_nacimiento date NOT NULL,
    id_categoria character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ingreso_empresa date NOT NULL,
    CONSTRAINT empleado_pkey PRIMARY KEY (rut)
);

CREATE TABLE IF NOT EXISTS public.horas_extra
(
    id integer NOT NULL,
    fecha date,
    rut integer NOT NULL,
    CONSTRAINT horas_extra_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ingresos
(
    rut integer NOT NULL,
    hora time without time zone NOT NULL,
    fecha date NOT NULL,
    id_ingresos integer NOT NULL,
    CONSTRAINT ingresos_pkey PRIMARY KEY (id_ingresos)
);

CREATE TABLE IF NOT EXISTS public.justificacion
(
    id integer NOT NULL,
    rut integer NOT NULL,
    fecha date NOT NULL,
    CONSTRAINT justificacion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.planilla
(
    id integer NOT NULL,
    anios_servicio integer NOT NULL,
    bonificacion integer NOT NULL,
    bruto integer NOT NULL,
    cotizacion_previsional integer NOT NULL,
    cotizacion_salud integer NOT NULL,
    horas_extra_monto integer NOT NULL,
    monto_descuento integer NOT NULL,
    nombre_empleado character varying(255) COLLATE pg_catalog."default",
    rut integer NOT NULL,
    sueldo_fijo integer NOT NULL,
    sueldo_final integer NOT NULL,
    CONSTRAINT planilla_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.empleado
    ADD CONSTRAINT empleado_fkey FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.horas_extra
    ADD CONSTRAINT rut FOREIGN KEY (rut)
    REFERENCES public.empleado (rut) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ingresos
    ADD CONSTRAINT rut FOREIGN KEY (rut)
    REFERENCES public.empleado (rut) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.justificacion
    ADD CONSTRAINT rut FOREIGN KEY (rut)
    REFERENCES public.empleado (rut) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;